config/routes.rb
Rails.application.routes.draw do

  scope module: :zendesk_ticket do
    post ZendeskTicket.route => 'tickets#create', as: 'zendesk_ticket'
  end

  

end

app/models/ticket.rb
class Ticket
  attr_reader :errors

  def initialize params
    @description = params[:description]
    @subject = params[:subject]
    @username = params[:username]
  end

  def save
    if is_client_authenticated?
      ticket = ZendeskAPI::Ticket.new client
      ticket.subject = @subject
      ticket.description = @description
      ticket.submitter_id = client.current_user.id
      if ticket.save
        @zendesk_ticket = ticket
        true
      else
        @errors = ticket.errors
        false
      end
    else
      @errors = { base: [ username: I18n.t('unauthorized', scope: 'zendesk_ticket.user.errors') ] }
      false
    end
  end

  def url
    if @zendesk_ticket.present? && @zendesk_ticket.id?
      base_url = URI::join(ZendeskTicket.url, '/').to_s
      "#{base_url}tickets/#{@zendesk_ticket.id}"
    end
  end

  private
  def client
    ZendeskAPI::Client.new do |config|
      config.url = ZendeskTicket.url
      config.username = @username
      config.token = ZendeskTicket.api_token
    end
  end

  def is_client_authenticated?
    client.current_user.id.present? # an invalid user still returns an user object, but has nil as an id
  end
end

app/controllers/zendesk_ticket/tickets_controller.rb
class ZendeskTicket::TicketsController < ActionController::Base
  respond_to :json
  layout :false

  def create
    ticket = Ticket.new ticket_params
    if ticket.save
      render json: { message:  I18n.t('created', scope: 'zendesk_ticket.ticket.success'), ticket: { url: ticket.url } }, status: :created
    else
      render json: { errors: ticket.errors }, status: :unprocessable_entity
    end
  end

  def ticket_params
    params.require(:ticket).permit :username, :description, :subject
  end
end

app/helpers/zendesk_ticket_helper.rb
module ZendeskTicketHelper
  def zendesk_ticket_translation_json
    I18n.backend.send(:init_translations) unless I18n.backend.initialized?
    translations = I18n.backend.send(:translations).with_indifferent_access
    if translations[I18n.locale][:zendesk_ticket].present?
      translations = translations[I18n.locale][:zendesk_ticket]
    else
      raise "Zendesk translations not found for locale: #{I18n.locale}. Please run rails generator zendesk_ticket:install or add the missing translations manually"
    end
    translations.to_json.html_safe
  end
end

app/views/zendesk_ticket/_button.html.erb
<button data-zendesk-ticket-button class="zendesk_ticket_sidebar_button"><%= I18n.t('new_ticket', scope: 'zendesk_ticket.buttons') %></button>

app/views/zendesk_ticket/_form.html.erb
<div class="form slide">
<h2><%= I18n.t('title', scope: 'zendesk_ticket.ticket.form') %></h2>
<%= form_tag ENV['ZENDESK_REMOTE_FORM_URL'] || zendesk_ticket_path, method: "post", class: "zendesk_ticket_form", novalidate: true, data: { "zendesk-ticket-form" => true } do %>
  <%= label_tag "ticket[username]", I18n.t('username', scope: 'zendesk_ticket.ticket.form.labels') %>
  <%= email_field :ticket, :username, placeholder: I18n.t('username', scope: 'zendesk_ticket.ticket.form.placeholders'), required: true %>

  <%= label_tag "ticket[subject]", I18n.t('subject', scope: 'zendesk_ticket.ticket.form.labels') %>
  <%= text_field :ticket, :subject, placeholder: I18n.t('subject', scope: 'zendesk_ticket.ticket.form.placeholders') %>

   <%= label_tag "ticket[description]", I18n.t('description', scope: 'zendesk_ticket.ticket.form.labels') %>
   <%= text_area_tag :description, nil, id: 'ticket_description', required: true, name: 'ticket[description]', size: "24x6", placeholder: I18n.t('description', scope: 'zendesk_ticket.ticket.form.placeholders') %>

  <%= submit_tag I18n.t('submit', scope: 'zendesk_ticket.ticket.form') %>
  <a href="javascript: " data-zendesk-ticket-close  class="zendesk_ticket_button" ><%= I18n.t('close', scope: 'zendesk_ticket.buttons') %></a>
<% end %>
<div class="clear"></div>
</div>

app/views/zendesk_ticket/_popup.html.erb
<script>
  window.I18n = <%= zendesk_ticket_translation_json %>
</script>
<div data-zendesk-ticket-popup-container class="zendesk_ticket_popup_container hidden">
  <div class="zendesk_ticket_popup">
    <div data-zendesk-ticket-slider class="zendesk_ticket_slides">
      <%= render "zendesk_ticket/form" %>
      <%= render "zendesk_ticket/thankyou" %>
    </div>
  </div>
</div>

app/views/zendesk_ticket/_thankyou.html.erb
<div class="thankyou slide">
  <h2><%= I18n.t('title', scope: 'zendesk_ticket.ticket.thankyou') %></h2>
  <p><%= I18n.t('link', scope: 'zendesk_ticket.ticket.thankyou') %> <span data-zendesk-ticket-url></span></p>
  <br />
<a href="javascript: " data-zendesk-ticket-back class="zendesk_ticket_button" ><%= I18n.t('create_another', scope: 'zendesk_ticket.ticket.thankyou') %></a>
<a href="javascript: " data-zendesk-ticket-close  class="zendesk_ticket_button"><%= I18n.t('close', scope: 'zendesk_ticket.buttons') %></a>
</div>